swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0'})

const outputFile = "./source/swagger_output.json"

//TODO get all ts files in routes
const path = require("path");
const fs = require("fs");

function throughDirectory(Directory) {
    fs.readdirSync(Directory).forEach(file => {
        const filename = path.join(Directory, file);
        const stat = fs.statSync(filename)
        if (stat.isDirectory()) return throughDirectory(filename);
        else if (path.extname(file).toLowerCase() == '.ts' && stat.size >= 100)
            return endpointsFiles.push(filename);
    });
}

// const endpointsFiles = ["./source/routes/sample.routing.ts"]
const endpointsFiles = []

throughDirectory("./source/");

console.log(endpointsFiles)

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:6060",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    definitions: {
        User: {
            name: "Jhon Doe",
            age: 29,
            parents: {
                father: "Simon Doe",
                mother: "Marie Doe"
            },
            diplomas: [
                {
                    school: "XYZ University",
                    year: 2020,
                    completed: true,
                    internship: {
                        hours: 290,
                        location: "XYZ Company"
                    }
                }
            ]
        },
        AddUser: {
            $name: "Jhon Doe",
            $age: 29,
            about: ""
        }
    }
}
swaggerAutogen(outputFile, endpointsFiles, doc)
